steps:
  - label: ":python: test"
    command: ./scripts/test
    env:
      CONDA_ENV_NAME: "md_dataset_package"
    agents:
      python-r-4.3: true

  - label: ":lint-roller: lint"
    command: ./scripts/lint
    env:
      CONDA_ENV_NAME: "md_dataset_package"
    agents:
      python-r-4.3: true

  - wait: ~
    key: prep

  ################################################################################
  ## Image
  ################################################################################
  - block: ":warning: build and push docker images?"
    key: block_image
    depends_on: prep
    branches: "!main"

  - label: ":docker: dataset package: build & push image"
    key: build_python_image
    depends_on: ["block_image", "prep"]
    command: scripts/build-push
    env:
      AWS_REGION: "ap-southeast-2"
      AWS_DEFAULT_REGION: "ap-southeast-2"
      AWS_PROFILE: "eb-services-cli"
      BUILD_NUMBER: "${BUILDKITE_BUILD_NUMBER}"
      DOCKER_FILE: "Dockerfile"
      REPO_NAME: "md_dataset_package"
      GIT_HASH: "${BUILDKITE_COMMIT}"
    agents:
      ebdeploy: true
    concurrency: 1
    concurrency_group: "md_dataset_package/docker"
